# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 9, 8, 2, 14, 37, 784417, tzinfo=utc))),
                ('time', models.TimeField(default=datetime.datetime(2017, 9, 8, 2, 14, 37, 784417, tzinfo=utc))),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
